# Vector Addition

In [1]:
import numpy as np

In [4]:
a = np.array([1,2])
b = np.array([3,4])

In [5]:
result = a+b
print(result)

[4 6]


# Vector multiplication

In [6]:
result = a*b
print(result)

[3 8]


# scalar multiplcation

In [7]:
alpha = 3
u = np.array([-1, 3])

In [9]:
scalar_mul = alpha * u
print(scalar_mul)

[-3  9]


# Dot Product

In [11]:
result = np.dot(a, b)
print(result)

11


# Cross Product

In [13]:
a = np.array([1,0,0])
b = np.array([0,1,0])

In [14]:
result = np.cross(a, b)
print(result)

[0 0 1]


# Norm of a Vector (Euclidean)

∥v∥ =√(3^2 + 4^2) = 5

In [16]:
v = np.array([3, 4])

In [17]:
result = np.linalg.norm(v)
print(result)

5.0


# Orthogonality Condition

In [18]:
u = np.array([1, 2])
v = np.array([-2, 1])

In [19]:
result = np.dot(u, v)
print(result)

0


In [21]:
is_orthogonal = result == 0
print(is_orthogonal)

True


 # Matrix Addition

In [22]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [23]:
result = A + B

In [24]:
print(result)

[[ 6  8]
 [10 12]]


# Matrix Scalar Multiplication

In [25]:
alpha = 2
A = np.array([[1, 2], [3, 4]])

In [26]:
result = alpha * A
print(result)

[[2 4]
 [6 8]]


# Matrix-Vector Multiplication

In [27]:
A = np.array([[1, 2], [3, 4]])
x = np.array([5, 6])

In [28]:
result = np.dot(A, x)
print(result)

[17 39]


# Matrix Multiplication

In [29]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [31]:
result = np.dot(A, B)
print(result)

[[19 22]
 [43 50]]


# Transpose of a Matrix

In [32]:
A = np.array([[1, 2], [3, 4]])
result = A.T
print(result)

[[1 3]
 [2 4]]


# Determinant of a 2×2 Matrix

In [33]:
A = np.array([[3, 8], [4, 6]])
result = np.linalg.det(A)
print(result)

-14.000000000000004


# Inverse of a 2×2 Matrix

In [34]:
A = np.array([[3, 8], [4, 6]])
result = np.linalg.inv(A)
print(result)

[[-0.42857143  0.57142857]
 [ 0.28571429 -0.21428571]]


# Cramer’s Rule

xi =det(Ai) / det(A), det(A) ̸= 0

In [37]:
A = np.array([[2, 1], [1, 3]])
b = np.array([5, 7])
det_A = np.linalg.det(A)
# Apply Cramer's rule
x = [
    np.linalg.det(np.column_stack([b if i == j else A[:, j] for j in range(A.shape[1])])) / det_A
    for i in range(A.shape[1])
]

print(x)

[1.5999999999999994, 1.8]


# Inverse of a Square Matrix

In [38]:
A = np.array([[4, 7], [2, 6]])
result = np.linalg.inv(A)
print(result)

[[ 0.6 -0.7]
 [-0.2  0.4]]


# Determinant of a Triangular Matrix

In [39]:
A = np.array([[2, 1, 0], [0, 3, 4], [0, 0, 5]])
result = np.prod(np.diag(A))

In [40]:
print(result)

30


# Rank-Nullity Theorem

The Rank-Nullity Theorem states that the sum of the rank (dimension 
of column space) and nullity (dimension of null space) of a matrix equals the number o 
colum.
ns

In [41]:
from numpy.linalg import matrix_rank

In [42]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
rank = matrix_rank(A)

In [43]:
nullity = A.shape[1] - rank
print(nullity)

1


# Hadamard (Elementwise) Product
The Hadamard product performs elementwise multiplication between
two matrices. It is used in ML for feature-wise scaling or gating.

In [44]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [45]:
result = np.multiply(A, B)
print(result)

[[ 5 12]
 [21 32]]


# Outer Product
The outer product generates a matrix by multiplying every element of
one vector by every element of another.

In [46]:
u = np.array([1, 2])
v = np.array([3, 4, 5])
result = np.outer(u, v)
print(result)

[[ 3  4  5]
 [ 6  8 10]]


# Frobenius Norm
The Frobenius norm measures the magnitude of a matrix by summing
the squares of all its elements

In [49]:
A = np.array([[1, 2], [3, 4]])
result = np.linalg.norm(A, 'fro')
print(result)

5.477225575051661


# Matrix Norm Inequality
* e ∥Ax∥ ≤ ∥A∥∥x∥.

In [50]:
A = np.array([[1, 2], [3, 4]])
x = np.array([1, 1])
left = np.linalg.norm(np.dot(A, x))
right = np.linalg.norm(A) * np.linalg.norm(x)

In [51]:
inequality_holds = left <= right
print(inequality_holds)

True


# Matrix Trace
The trace of a matrix is the sum of its diagonal elements
Tr(A) = 1 + 4 = 5ii

In [53]:
A = np.array([[1, 2], [3, 4]])
result = np.trace(A)
print(result)

5


# Trace of a Product
* Tr(AB) = Tr(BA)

In [59]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [60]:
trace1 = np.trace(np.dot(A, B))
trace2 = np.trace(np.dot(B, A))

In [61]:
equality_holds = trace1 == trace2
print(equality_holds)

True


# Block Matrix Multiplication
Block matrix multiplication follows the same rules as scalar matrix
multiplication, but each element is a submatrix

In [62]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.array([[9, 10], [11, 12]])
D = np.array([[13, 14], [15, 16]])
E = np.array([[17, 18], [19, 20]])
F = np.array([[21, 22], [23, 24]])
G = np.array([[25, 26], [27, 28]])
H = np.array([[29, 30], [31, 32]])

In [63]:
top_left = np.dot(A, E) + np.dot(B, G)
top_right = np.dot(A, F) + np.dot(B, H)
bottom_left = np.dot(C, E) + np.dot(D, G)
bottom_right = np.dot(C, F) + np.dot(D, H)

In [65]:
result = np.block([[top_left, top_right], [bottom_left, bottom_right]])
print(result)

[[ 342  356  398  412]
 [ 518  540  606  628]
 [1046 1092 1230 1276]
 [1222 1276 1438 1492]]


# Kronecker Product
The Kronecker product produces a block matrix by multiplying each
element of one matrix by the entirety of another.

In [66]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[0, 5], [6, 7]])

In [67]:
result = np.kron(A, B)
print(result)

[[ 0  5  0 10]
 [ 6  7 12 14]
 [ 0 15  0 20]
 [18 21 24 28]]
