Batch Normalization is a technique to normalize the inputs of each layer in a neural network across a mini-batch during training. It stabilizes and accelerates training by reducing internal covariate shift.

In [1]:
import numpy as np

def batch_norm_forward(X, gamma, beta, epsilon=1e-5):
    # Step 1: calculate mean
    mu = np.mean(X, axis=0)
    
    # Step 2: subtract mean vector from each input
    X_mu = X - mu
    
    # Step 3: calculate variance
    var = np.var(X, axis=0)
    
    # Step 4: normalize
    std = np.sqrt(var + epsilon)
    X_hat = X_mu / std
    
    # Step 5: scale and shift
    out = gamma * X_hat + beta
    
    return out, X_hat, mu, var, std


In [2]:
# Simulated batch input
X = np.array([[1.0, 2.0],
              [2.0, 3.0],
              [3.0, 4.0]])

# Initialize gamma and beta
gamma = np.ones(X.shape[1])
beta = np.zeros(X.shape[1])

# Apply Batch Norm
out, X_hat, mu, var, std = batch_norm_forward(X, gamma, beta)

print("Normalized Output:\n", out)


Normalized Output:
 [[-1.22473569 -1.22473569]
 [ 0.          0.        ]
 [ 1.22473569  1.22473569]]


### Dropout Regularization
Dropout is a regularization technique that randomly sets a fraction of neuron outputs to zero during training. It prevents overfitting by discouraging complex co-adaptations on training data.

In [3]:
import numpy as np

def dropout_forward(A, keep_prob=0.8):
    # Generate mask (same shape as A)
    dropout_mask = (np.random.rand(*A.shape) < keep_prob).astype(np.float32)
    
    # Apply mask and scale
    A_dropout = (A * dropout_mask) / keep_prob
    
    return A_dropout, dropout_mask
np.random.seed(42)

# Simulated activation matrix
A = np.array([[1.0, 2.0, 3.0],
              [4.0, 5.0, 6.0]])

A_dropout, mask = dropout_forward(A, keep_prob=0.5)

print("Original Activations:\n", A)
print("Dropout Mask:\n", mask)
print("After Dropout:\n", A_dropout)

Original Activations:
 [[1. 2. 3.]
 [4. 5. 6.]]
Dropout Mask:
 [[1. 0. 0.]
 [0. 1. 1.]]
After Dropout:
 [[ 2.  0.  0.]
 [ 0. 10. 12.]]
